//
// Created by Nhat Bui on 10/12/2022.
//

#ifndef SIMPLEHTTPSERVER_SRC_INCLUDE_NETWORKING_HTTP_MESSAGE_DEFINE_H_
#define SIMPLEHTTPSERVER_SRC_INCLUDE_NETWORKING_HTTP_MESSAGE_DEFINE_H_

enum class HttpMethod {
  GET,
  HEAD,
  POST,
  PUT,
  DELETE,
  CONNECT,
  OPTIONS,
  TRACE,
  PATCH
};

enum class HttpVersion {
  HTTP_0_9,
  HTTP_1_0,
  HTTP_1_1,
  HTTP_2_0
};

enum class HttpStatusCode {
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  EARLY_HINTS = 103,
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOTFOUND = 404,
  MULTILE_CHOISES = 300,
  MOVE_PERMANENTLY = 301,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  HTTP_VERSION_NOT_SUPPORTED = 505
};


#endif//SIMPLEHTTPSERVER_SRC_INCLUDE_NETWORKING_HTTP_MESSAGE_DEFINE_H_
