//
// Created by Nhat Bui on 10/12/2022.
//

#ifndef SIMPLEHTTPSERVER_SRC_INCLUDE_NETWORKING_LOGGER_H_
#define SIMPLEHTTPSERVER_SRC_INCLUDE_NETWORKING_LOGGER_H_

#endif//SIMPLEHTTPSERVER_SRC_INCLUDE_NETWORKING_LOGGER_H_
