//
// Created by nhatbui on 09/12/2022.
//

#ifndef SIMPLEHTTPSERVER_SRC_INCLUDE_NETWORKING_MESSAGE_PARSER_H_
#define SIMPLEHTTPSERVER_SRC_INCLUDE_NETWORKING_MESSAGE_PARSER_H_

class MessageParser {
};

#endif//SIMPLEHTTPSERVER_SRC_INCLUDE_NETWORKING_MESSAGE_PARSER_H_
